#!/bin/bash


# Author: Carlos Camilleri-Robles
# Contact: carloscamilleri@hotmail.com
# This script uses deeptools to generate bigwig files. The script is optimized for single-end sequencing.

set -e


## Variable set up
INPUT_DIR="Histone_ChIPseq/Mapped/Sorted"
OUTPUT_DIR="Histone_ChIPseq/Mapped/Bigwig"


## Options
EXTEND=150               # Read extension (for single-end only)
NORMALIZE="CPM"          # Normalization method applied (CPM, RPGC, BPM, None)
BINSIZE=50               # Bin size (base pairs)


mkdir -p $OUTPUT_DIR


for bam_file in $INPUT_DIR/*.bam; do
	base_name=$(basename "$bam_file" _sorted.bam)
	bw_file="$OUTPUT_DIR/${base_name}.bw"
	echo "Converting $bam_file..."
	bamCoverage -b "$bam_file" -o "$bw_file" --normalizeUsing $NORMALIZE --extendReads $EXTEND --binSize $BINSIZE
done

echo "All bigwig files generated."
